# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-24 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('group', models.CharField(max_length=255)),
                ('reader', models.CharField(db_index=True, max_length=255)),
                ('sentence', models.IntegerField(db_index=True)),
            ],
        ),
    ]
