# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/postgres:9.6 # https://circleci.com/docs/2.0/postgres-config/

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install R deps
          command: |
            sudo apt-get install r-base-core unzip
            cd R
            curl -O http://mayekawa.in.coocan.jp/Rpackages/lazy.mat_0.1.3.zip
            curl -O http://mayekawa.in.coocan.jp/Rpackages/lazy.tools_0.1.3.zip
            curl -O http://mayekawa.in.coocan.jp/Rpackages/lazy.mdpref_0.1.2.zip
            unzip -x lazy.mat_0.1.3.zip
            unzip -x lazy.tools_0.1.3.zip
            unzip -x lazy.mdpref_0.1.2.zip
            sudo Rscript -e "install.packages('naturalsort')"
            sudo R CMD INSTALL lazy.mat
            sudo R CMD INSTALL lazy.tools
            sudo R CMD INSTALL lazy.mdpref
            sudo Rscript -e "source(\"http://bioconductor.org/biocLite.R\"); biocLite(\"pcaMethods\")"
            cd ..

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements/test.txt
            pip install -r requirements/production.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements/test.txt" }}

      # run tests!
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python manage.py test
          post:
            - bash <(curl -s https://codecov.io/bash)

      - store_artifacts:
          path: test-reports
          destination: test-reports
      # https://medium.com/@kirill_shevch/continuous-deployment-with-circleci-and-capistrano-for-web-applications-d8fea0192114
