# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-24 05:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_gt_b', models.BooleanField()),
                ('audio_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_a_fk', to='audio.Audio')),
                ('audio_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_b_fk', to='audio.Audio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
